apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: checkout-api
  namespace: demo
  labels:
    release: prometheus
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selector:
    matchLabels:
      app: checkout-api
  namespaceSelector:
    matchNames:
      - demo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s